// Kurz-Ausführungshinweise je Übung (Standard-Technikwissen). complex=Video empfohlen.
export const EXERCISE_INFO = {
  "ringdips": { t: "Wie Dips, aber an Ringen — die instabilen Ringe fordern viel mehr Rumpf- und Schulterkontrolle. Ringe eng am Körper, kontrolliert tief. Fehler: Ringe wackeln/spreizen, zu tief bei Schulterproblemen.", c: true },
  "bench_lh": { t: "Schulterblätter zusammenziehen, Stange zur unteren Brust senken, Ellbogen ~45°. Fehler: Ellbogen zu weit abspreizen, Hintern hebt ab.", c: false },
  "bench_kh": { t: "Hanteln über der Brust, kontrolliert tief für mehr Dehnung, dann zusammendrücken. Fehler: zu tiefes Durchhängen ohne Kontrolle.", c: false },
  "chestpress_m": { t: "Aufrecht sitzen, Griffe auf Brusthöhe, gleichmäßig wegdrücken. Fehler: Schultern nach vorne ziehen statt stabil halten.", c: false },
  "chestpress_c": { t: "Leichte Vorlage, Griffe vor der Brust zusammenführen, Spannung halten. Fehler: nur aus den Armen statt aus der Brust.", c: false },
  "incline_lh": { t: "Bank 30–45°, Stange zur oberen Brust, Schulterblätter fixiert. Fehler: zu steile Bank macht es zur Schulterübung.", c: false },
  "incline_kh": { t: "Schrägbank, Hanteln zur oberen Brust, voller Bewegungsumfang. Fehler: Hanteln nach innen kippen.", c: false },
  "incline_m": { t: "Schräg sitzend gleichmäßig drücken, Brust vorne. Fehler: Lendenwirbel ins Hohlkreuz pressen.", c: false },
  "dips": { t: "Leicht vorlehnen für Brustfokus, kontrolliert bis Oberarm waagerecht. Fehler: zu tief bei Schulterproblemen.", c: false },
  "pushup": { t: "Körper bleibt eine Linie, Ellbogen ~45°, Brust fast zum Boden. Fehler: Hüfte hängt durch oder schiebt hoch.", c: false },
  "flyes_c": { t: "Leichte Ellbogenbeugung halten, Arme im Bogen zusammenführen. Fehler: zu schwer, daraus wird eine Druckbewegung.", c: false },
  "flyes_kh": { t: "Bogenbewegung mit fixiertem Ellbogenwinkel, Dehnung spüren. Fehler: Ellbogen durchstrecken/abknicken.", c: false },
  "pecdeck": { t: "Aufrecht, Unterarme/Polster führen zusammen, Brust anspannen. Fehler: nur mit den Händen drücken.", c: false },
  "pullup": { t: "Voller Hang, Schulterblätter zuerst, Brust zur Stange. Fehler: nur halb hochziehen, schwingen.", c: false },
  "weightedpull": { t: "Wie Klimmzug mit Zusatzgewicht, sauber voller Bewegungsumfang. Fehler: Gewicht erhöhen auf Kosten der Technik.", c: false },
  "chinup": { t: "Untergriff, Ellbogen nach unten ziehen, Bizeps & Rücken. Fehler: Kinn mit Schwung über die Stange reißen.", c: false },
  "pulldown_w": { t: "Weiter Griff, Stange zur oberen Brust, Brust raus. Fehler: stark zurücklehnen und reißen.", c: false },
  "pulldown_c": { t: "Enger/neutraler Griff, zur Brust ziehen, Lat anspannen. Fehler: nur die Arme statt den Rücken nutzen.", c: false },
  "row_lh": { t: "Hüfte gebeugt, Rücken neutral, Stange zum Bauchnabel. Fehler: runder Rücken, Schwung aus der Hüfte.", c: false },
  "row_kh": { t: "Abgestützt, Hantel zur Hüfte, Schulterblatt zurück. Fehler: Oberkörper mitdrehen/hochreißen.", c: false },
  "row_c": { t: "Aufrecht sitzen, Griff zum Bauch, Brust raus, Schultern zurück. Fehler: mit dem Oberkörper pumpen.", c: false },
  "row_m": { t: "Brust ans Polster, Griffe nach hinten ziehen. Fehler: Schultern hochziehen statt zurück.", c: false },
  "row_tbar": { t: "Neutraler Rücken, Gewicht eng am Körper hochziehen. Fehler: runder Rücken bei zu viel Last.", c: false },
  "ohp_lh": { t: "Stange aus Schulterhöhe gerade nach oben, Core fest, Po fest. Fehler: starkes Hohlkreuz, Stange zu weit vorn.", c: false },
  "ohp_kh": { t: "Hanteln aus Ohrhöhe nach oben, Handgelenke stabil. Fehler: ins Hohlkreuz ausweichen.", c: false },
  "ohp_m": { t: "Aufrecht, Griffe nach oben drücken, Schultern unten lassen. Fehler: Schultern hochziehen.", c: false },
  "pushpress": { t: "Leichter Beinimpuls, dann explosiv nach oben drücken. Fehler: zu viel Knie, daraus wird Kniebeuge.", c: false },
  "latraise_kh": { t: "Leicht vorgebeugt, Arme seitlich bis Schulterhöhe, kleiner Ellbogenknick. Fehler: Schwung, Schultern hochziehen.", c: false },
  "latraise_c": { t: "Kabel von unten, seitlich bis waagerecht, langsam ab. Fehler: zu schwer, Körper schwingt.", c: false },
  "rearfly_kh": { t: "Vorgebeugt, Arme im Bogen nach hinten/oben, hintere Schulter. Fehler: Rücken statt Schulter führt.", c: false },
  "facepull": { t: "Seil zum Gesicht ziehen, Ellbogen hoch, außenrotieren. Fehler: zu schwer, Ellbogen sinken ab.", c: false },
  "squat_lh": { t: "Stange stabil, Hüfte & Knie gleichzeitig beugen, Knie Richtung Zehen, mind. Hüfte unter Knie. Fehler: Knie kippen nach innen, Rücken rundet.", c: false },
  "frontsquat": { t: "Stange auf vorderen Schultern, Ellbogen hoch, aufrecht tief. Fehler: Ellbogen sinken, Oberkörper kippt vor.", c: false },
  "gobletsquat": { t: "Hantel vor der Brust, aufrecht tief, Knie raus. Fehler: nach vorne kippen.", c: false },
  "hacksquat": { t: "Rücken am Polster, tief kontrolliert, Knie folgen den Zehen. Fehler: nur Teilbewegung, Fersen heben.", c: false },
  "legpress": { t: "Füße schulterbreit, bis ~90° beugen, Rücken am Polster. Fehler: Knie zur Brust, Lende rundet ab.", c: false },
  "lunges": { t: "Großer Schritt, hinteres Knie Richtung Boden, Oberkörper aufrecht. Fehler: vorderes Knie über die Zehen kippen.", c: false },
  "bulgarian": { t: "Hinterer Fuß erhöht, vorderes Bein tief, aufrecht. Fehler: zu kurzer Stand, Knie kippt nach innen.", c: false },
  "pausesquat": { t: "Kniebeuge mit 1–2 s Pause unten ohne Spannungsverlust. Fehler: in der Pause locker lassen.", c: false },
  "legext": { t: "Aufrecht sitzen, Beine kontrolliert strecken, oben kurz halten. Fehler: schwungvoll hochwerfen.", c: false },
  "deadlift": { t: "Stange eng am Schienbein, Rücken neutral, mit Beinen & Hüfte drücken/strecken. Fehler: runder Rücken, Hüfte schießt hoch.", c: false },
  "rdl_lh": { t: "Leichte Kniebeugung, Hüfte zurück, Stange eng führen, Dehnung hinten. Fehler: aus dem Rücken statt der Hüfte.", c: false },
  "rdl_kh": { t: "Hüfte zurück, Hanteln eng am Bein, Rücken gerade. Fehler: Knie zu stark beugen, Rücken rundet.", c: false },
  "goodmorning": { t: "Leichte Knie, Hüfte zurück, Oberkörper neigen, Rücken fest. Fehler: zu schwer, Rücken rundet.", c: false },
  "hipthrust": { t: "Oberer Rücken auf Bank, Hüfte voll strecken, Po fest, Kinn an. Fehler: ins Hohlkreuz statt Hüftstreckung.", c: false },
  "legcurl_l": { t: "Bäuchlings, Fersen zum Po, kontrolliert ab. Fehler: Hüfte abheben, Schwung.", c: false },
  "legcurl_s": { t: "Sitzend Fersen unterziehen, oben anspannen. Fehler: nur Teilbewegung.", c: false },
  "hyper": { t: "Hüfte als Drehpunkt, Rücken neutral, bis Linie hochkommen. Fehler: überstrecken ins Hohlkreuz.", c: false },
  "calf_st": { t: "Voller Bewegungsumfang, oben kurz halten, tief dehnen. Fehler: schnelles Wippen ohne Dehnung.", c: false },
  "calf_se": { t: "Sitzend Knie 90°, Wade voll strecken und dehnen. Fehler: nur kurze Teilbewegung.", c: false },
  "curl_lh": { t: "Ellbogen am Körper, Stange hochcurlen ohne Schwung. Fehler: mit dem Rücken nachhelfen.", c: false },
  "curl_kh": { t: "Wechselnd oder beidseitig, oben drehen, kontrolliert ab. Fehler: Ellbogen nach vorne wandern.", c: false },
  "curl_c": { t: "Konstante Kabelspannung, sauber curlen. Fehler: Körper schwingt mit.", c: false },
  "hammercurl": { t: "Neutraler Griff, Ellbogen fix, hochcurlen. Fehler: Schwung aus der Schulter.", c: false },
  "preacher": { t: "Oberarme auf Polster, voll strecken & beugen. Fehler: unten ruckartig abfälschen.", c: false },
  "triceps_c": { t: "Ellbogen am Körper, nur Unterarm bewegt, unten strecken. Fehler: Ellbogen wandern, Oberkörper drückt.", c: false },
  "overheadtri": { t: "Ellbogen hoch & eng, hinter dem Kopf dehnen, strecken. Fehler: Ellbogen spreizen.", c: false },
  "skullcrusher": { t: "Oberarme senkrecht, Stange zur Stirn senken, strecken. Fehler: ganze Arme bewegen.", c: false },
  "cgbench": { t: "Engerer Griff, Ellbogen eng am Körper, Trizepsfokus. Fehler: Griff zu eng (Handgelenke).", c: false },
  "legraise": { t: "Hängend Beine kontrolliert heben, Becken kippen. Fehler: schwingen, nur aus der Hüfte.", c: false },
  "plank": { t: "Körper eine Linie, Bauch & Po fest, normal atmen. Fehler: Hüfte hängt durch oder schiebt hoch.", c: false },
  "cablecrunch": { t: "Seil am Kopf, mit dem Bauch einrollen, Hüfte fix. Fehler: aus der Hüfte ziehen statt einrollen.", c: false },
  "abwheel": { t: "Langsam ausrollen, Rücken neutral, Bauch fest. Fehler: Hohlkreuz beim Ausrollen.", c: false },
  "snatch": { t: "Explosiv von Boden in einer Bewegung über den Kopf, tiefe Hocke. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "cleanjerk": { t: "Umsetzen auf die Schultern, dann explosiv über Kopf stoßen. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "powerclean": { t: "Explosiv vom Boden auf die Schultern, kein tiefes Fangen. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "powersnatch": { t: "Explosiv vom Boden über Kopf, hoch gefangen. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "hangclean": { t: "Aus dem Hang explosiv auf die Schultern. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "overheadsquat": { t: "Stange über Kopf gestreckt, tiefe Kniebeuge, viel Mobilität. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "pushjerk": { t: "Beinimpuls, unter die Stange tauchen, Arme strecken. KOMPLEX – mit Anleitung/Video lernen.", c: true },
  "thruster": { t: "Frontkniebeuge direkt in Überkopfdrücken verbinden, flüssig. Fehler: Bewegungen abhacken statt verbinden.", c: false },
  "wallball": { t: "Tiefe Kniebeuge, explosiv hoch und Ball zum Ziel werfen. Fehler: nur aus den Armen werfen.", c: false },
  "burpee": { t: "Brust zum Boden, hochspringen, Hände über Kopf. Fehler: durchhängende Hüfte am Boden.", c: false },
  "boxjump": { t: "Mit beiden Beinen abdrücken, weich auf der Box landen, aufrichten. Fehler: zu hohe Box, harte Landung.", c: false },
  "kbswing": { t: "Hüftschwung treibt die Kettlebell, Arme nur Führung, Po fest. Fehler: mit den Armen heben statt Hüfte.", c: false },
  "kbsnatch": { t: "Aus dem Schwung in einer Bewegung über den Kopf. KOMPLEX – mit Anleitung lernen.", c: true },
  "sledpush": { t: "Tiefe Körperlage, gleichmäßig schieben, kräftige Schritte. Fehler: aufrecht stehen, kein Vortrieb.", c: false },
  "sledpull": { t: "Stabiler Stand, mit ganzem Körper ziehen. Fehler: nur mit den Armen reißen.", c: false },
  "farmers": { t: "Schwere Hanteln seitlich, aufrecht & stabil gehen, Schultern zurück. Fehler: nach vorne kippen, Schultern hängen.", c: false },
  "sandbag": { t: "Sandsack umarmen, aufrecht ausfallen, Core fest. Fehler: Rücken rundet unter Last.", c: false },
  "doubleunders": { t: "Seil zweimal pro Sprung, aus den Handgelenken, kleiner Sprung. Fehler: zu hoch springen, aus den Armen.", c: false },
  "run": { t: "Aufrechte Haltung, lockere Schultern, gleichmäßiger Atem. Fehler: zu schnell starten.", c: false },
  "jogging": { t: "Lockeres Tempo, du kannst dich noch unterhalten (Zone 2). Fehler: zu intensiv für Grundlage.", c: false },
  "sprint": { t: "Maximale Intervalle mit voller Pause dazwischen. Fehler: ohne Aufwärmen sprinten.", c: false },
  "row_erg": { t: "Beine drücken zuerst, dann Rumpf, dann Arme – umgekehrt zurück. Fehler: nur mit Armen ziehen.", c: false },
  "ski_erg": { t: "Aus Rumpf & Lat nach unten ziehen, Hüfte mitnutzen. Fehler: nur Arme.", c: false },
  "bike_erg": { t: "Gleichmäßige Trittfrequenz, Arme bei Bedarf einsetzen. Fehler: zu hoher Widerstand, Technik leidet.", c: false },
  "stairmaster": { t: "Aufrecht, nicht aufs Geländer stützen, gleichmäßig steigen. Fehler: festhalten und entlasten.", c: false },
  "incline_walk": { t: "Steigung gehen, aufrecht, ohne Festhalten. Fehler: ans Gerät hängen.", c: false },
  "swimming": { t: "Gleichmäßige Bahnen, ruhige Atmung. Fehler: zu hektischer Stil.", c: false },
  "speedrope": { t: "Kleine Sprünge aus den Handgelenken, lockere Arme. Fehler: zu hoch springen.", c: false },
  "tireflip": { t: "Tief greifen, mit Beinen & Hüfte hochheben, dann umkippen. Fehler: aus rundem Rücken ziehen.", c: true },
  "atlasstone": { t: "Stein eng am Körper, aus der Hüfte hoch auf Schulter/Plattform. Fehler: Rücken rundet, Stein zu weit weg.", c: true },
  "yoke": { t: "Yoke auf den Schultern, Core fest, kurze stabile Schritte. Fehler: zu lange Schritte, Schwanken.", c: true },
  "logpress": { t: "Log auf die Schultern, Beinimpuls, über Kopf stoßen. Fehler: ins Hohlkreuz drücken.", c: true },
  "ropeclimb": { t: "Beine klemmen das Seil, mit den Beinen hochdrücken, Arme führen. Fehler: nur mit Armen ziehen.", c: true },
  "devilspress": { t: "Hanteln vom Boden per Burpee über den Kopf. Fehler: Rücken rundet beim Hochziehen.", c: true },
  "manmaker": { t: "Liegestütz mit Rudern, dann Clean zu Überkopfdrücken. Fehler: Hüfte schwingt, Technik bricht.", c: true },
  "dballclean": { t: "Ball aus der Hüfte explosiv auf die Schulter. Fehler: aus dem Rücken heben.", c: true },
  "turkishget": { t: "Vom Liegen kontrolliert zum Stand, Gewicht stabil oben. KOMPLEX – mit Anleitung lernen.", c: true },
  "kbclean": { t: "Kettlebell aus dem Schwung sauber in die Rack-Position. Fehler: auf den Unterarm knallen.", c: true },
  "stepup": { t: "Ganzer Fuß auf der Box, kontrolliert hoch über das Standbein. Fehler: mit hinterem Bein abdrücken.", c: false },
  "prowler": { t: "Tiefe Lage, kräftige Schritte, Schlitten schieben. Fehler: aufrecht ohne Vortrieb.", c: false },
  "broadjump": { t: "Mit Armschwung weit nach vorne springen, weich landen. Fehler: harte Landung mit gestreckten Knien.", c: false },
  "ghdsitup": { t: "Kontrolliert ablassen & aufkommen, Core führt. Fehler: zu weit überstrecken (Rücken).", c: true },
  "toestobar": { t: "Aus dem Hang mit Körperspannung Füße zur Stange. Fehler: nur schwingen.", c: true },
  "wallwalk": { t: "Mit den Füßen die Wand hochlaufen Richtung Handstand. KOMPLEX – mit Anleitung lernen.", c: true },
  "hspu": { t: "Handstand an der Wand, Kopf kontrolliert absenken, drücken. KOMPLEX – mit Anleitung lernen.", c: true },
  "battlerope": { t: "Aus stabilem Stand kräftige Wellen erzeugen, Core fest. Fehler: nur aus den Armen.", c: false },
  "assaultrun": { t: "Aufrecht, gleichmäßiger Schritt, kontrolliertes Tempo. Fehler: zu schnell starten.", c: false },
  "handstand": { t: "An der Wand Balance & Körperspannung aufbauen, Schultern aktiv. KOMPLEX – mit Anleitung lernen.", c: true },
  "planche": { t: "Fortgeschrittener Stütz mit Vorlage; nur progressiv aufbauen. KOMPLEX – mit Anleitung lernen.", c: true },
  "frontlever": { t: "Körper waagerecht am Hang, voll gespannt; Progressionen nutzen. KOMPLEX – mit Anleitung lernen.", c: true },
  "backlever": { t: "Rücklings waagerecht, langsam in Progressionen. KOMPLEX – mit Anleitung lernen.", c: true },
  "muscleup": { t: "Expliziter Zug, Übergang über die Stange in den Stütz. KOMPLEX – mit Anleitung lernen.", c: true },
  "oap": { t: "Einarmiger Liegestütz, breiter Stand, viel Rumpfspannung. KOMPLEX – mit Anleitung lernen.", c: true },
  "lsit": { t: "Gestreckte Beine vorhalten, Schultern runterdrücken. Fehler: runder Rücken, Schultern hoch.", c: true },
  "pistol": { t: "Einbeinige Kniebeuge tief & kontrolliert, Balance halten. KOMPLEX – mit Anleitung lernen.", c: true },
};